name: Test Repo Build
on:
  workflow_dispatch:
  push:
    branches:
      - "main"
jobs:
  version_bump:
    permissions:
      contents: write
    name: "Bump Version on develop"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          npm version patch
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "bump version in develop"
          git push

        # - name: "Automated Version Bump"
        #   id: version-bump
        #   uses: "phips28/gh-action-bump-version@master"
        #   with:
        #     skip-tag: true
        # env:
        #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # - name: "üè∑Ô∏è Create new git tag"
      #   run: ./scripts/tagme
